name: ci
on: [push]
jobs:
  build:
    name: Build (go ${{ matrix.go }}/${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.12', '1.13' ]
        os: [ 'ubuntu-latest', 'macos-latest' ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: CI
        run: make ci